// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmWKROL-hflzuuD1X5hOG9waw3Mg9VXCM',
    appId: '1:421108384902:web:3a67e30d795e27aa2b3d07',
    messagingSenderId: '421108384902',
    projectId: 'chat-f6098',
    authDomain: 'chat-f6098.firebaseapp.com',
    storageBucket: 'chat-f6098.appspot.com',
    measurementId: 'G-TJZ5ET24K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWPejnS_7eh25fVpbjX4YusEtjgWQQQy0',
    appId: '1:421108384902:android:530428ca553059b32b3d07',
    messagingSenderId: '421108384902',
    projectId: 'chat-f6098',
    storageBucket: 'chat-f6098.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdL7IYcuNnKTPPM-6VoQjmWtmYKPiYgYE',
    appId: '1:421108384902:ios:b5a526c5b9d3bd0d2b3d07',
    messagingSenderId: '421108384902',
    projectId: 'chat-f6098',
    storageBucket: 'chat-f6098.appspot.com',
    iosBundleId: 'com.example.chatTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdL7IYcuNnKTPPM-6VoQjmWtmYKPiYgYE',
    appId: '1:421108384902:ios:3fad139fca231ef42b3d07',
    messagingSenderId: '421108384902',
    projectId: 'chat-f6098',
    storageBucket: 'chat-f6098.appspot.com',
    iosBundleId: 'com.example.chatTask.RunnerTests',
  );
}
